/**
 * AOK (Agent Operating Kernel) Configuration
 * Generated by `aok init`
 */
module.exports = {
  // Command to execute the project validation loop
  testCommand: "",
  
  // Maximum number of repair iterations per failure before circuit breaks
  maxRepairAttempts: 4,
  
  // High-risk controlled refactoring engine (off by default)
  enableExploration: false,
  
  // Enforce strict UI safeguards when analyzing UX issues
  strictUXMode: true,
  
  // Location of AOK memory store
  memoryPath: ".aok/memory"
};
